### PR TITLE
Challenge

### PR DESCRIPTION
**Pull request by mitchellblom**

### CODE REVIEW

**Comment by mitchellblom** [comment]
Slacked @zoeames that this is ready to review.

**Comment by zoeames** [comment]
@mitchellblom Very nice quiz!!!!!  You are just missing 2 requirements.  1.  You need a standard bootstrap navbar.  2.  your cards should be arranged using bootstrap rows - 3 cards to a row

**Comment by mitchellblom** [comment]
@zoeames ready for final review once you're back from break.

**Comment by mitchellblom** [comment]
Thanks Zoe! Both revisions have now been made, plus some other styling fun.
Have a restful break, and I'll see you Monday night!

**Comment by zoeames** [comment]
looks good to me! 👍

**Pull request merged**
